'use client'

import { useState } from 'react'
import { FaArrowLeft, FaBell, FaCheck, FaCircleInfo, FaClock, FaComment, FaHeadset, FaHeart, FaLock, FaPlus, FaReceipt, FaTrophy, FaUpload, FaWallet } from 'react-icons/fa6'
import { PageHeader, BottomNav } from './app-shell'
import { EmptyState, ProgressBar, SectionLabel } from './shared'
import './final-screens.css'

function Frame({ title, subtitle, children, action }: { title: string; subtitle?: string; children: React.ReactNode; action?: React.ReactNode }) { return <><PageHeader title={title} subtitle={subtitle} action={action}/><main className="final-content">{children}</main><BottomNav/></> }
const updates=[['Promo Code Hours','Promo codes now pause 12:00 AM–8:00 AM PKT and reopen automatically with a live countdown','gold'],['Withdrawal Hours','Withdrawals now pause 12:00–12:30 AM PKT for profit distribution, with a live countdown until they reopen','red'],['Notifications Fixed','Now works after app updates','green'],['Weekly League — New!','Compete weekly, win cash prizes','green'],['Fresh Dashboard Design','Cleaner icons for Community, Salary & more','purple'],['Minor Design Upgrades','Polished UI touches across multiple screens — cleaner layout, better spacing, and improved visual consistency','purple'],['Live Withdrawal Counter','Watch your withdrawal being processed in real time — live countdown so you always know exactly when your money arrives','green'],['In-Chat Music System','Play music directly inside group chats — share and listen to tracks without leaving the conversation','blue']]
export function FinalWhatsNew(){return <Frame title="What&apos;s New" subtitle="Version history & updates"><div className="updates-card">{updates.map(([a,b,t])=><article key={a}><span className={`update-icon ${t}`}><FaBell/></span><div><strong>{a}</strong><p>{b}</p></div></article>)}</div><SectionLabel>v1.4 · 2 July 2026</SectionLabel></Frame>}
const league=[['Abbas','A',23],['Anila','A',23],['Fidahussain Hussain','F',22],['Pervaz Akhtar','P',22],['Sonjya kumari','S',21],['Malik Khawar','M',21],['Mr Muzamil','M',20],['Dur Mohammad','D',20],['Haroon Abbas','H',20]]
export function FullLeague(){return <Frame title="Weekly League" subtitle="Compete every week for prizes"><div className="league-list-final">{league.map(([name,initial,points],i)=><article key={name}><b>{i+11}</b><span>{initial}</span><div><strong>{name}</strong><small>This week&apos;s points</small></div><em>{points}</em></article>)}</div></Frame>}
export function LeaguePodium(){return <Frame title="Weekly League" subtitle="Compete every week for prizes"><div className="podium-hero"><strong>🥉 &nbsp; YOUR LEAGUE</strong><h2>Bronze</h2><p>Rank #174 of 393</p><div className="podium-stats"><span><b>0</b>Self</span><span><b>0</b>Referral</span><span><b>1</b>Login</span><span><b>1</b>Total</span></div></div><div className="podium"><b>🏆 THIS WEEK&apos;S TOP 3</b><div className="podium-people"><span>T<br/><strong>Tamjeed khokhar</strong><i>#2</i></span><span className="winner">S<br/><strong>Shamsa haiab</strong><i>#1</i></span><span>M<br/><strong>Moazam</strong><i>#3</i></span></div></div></Frame>}
export function Transactions(){return <Frame title="Transactions" subtitle="All wallet activity"><div className="filter-row"><b><FaReceipt/> All</b><span>↓ Deposit</span><span>↑ Withdrawal</span><span>▣ Profit</span></div><EmptyState title="No transactions found" icon={<FaReceipt/>}/></Frame>}
export function WithdrawalHistory(){return <Frame title="Withdrawal History" subtitle="All your withdrawal records"><EmptyState title="No withdrawals yet" icon={<FaReceipt/>}/></Frame>}
export function Support(){return <Frame title="Help & Support" subtitle="All caught up!" action={<button className="green-square"><FaPlus/></button>}><div className="filter-row"><b>All</b><span>Open</span><span>Answered</span><span>Closed</span></div><div className="support-empty"><span><FaHeadset/></span><h2>No Tickets Yet</h2><p>Need help? Create your first support ticket</p><button><FaPlus/> Create Ticket</button><a><FaComment/> Or start a Live Chat instead</a></div></Frame>}
export function WithdrawalProofs(){return <Frame title="Withdrawal Proofs"><div className="proof-card"><header><span>TA</span><div><strong>Talibh ✓</strong><small>EasyPaisa</small></div><b>Rs. 1,419</b></header><div className="proof-image">✓<strong>Withdrawal Approved!</strong><small>Your funds are on the way</small></div><footer><FaHeart/><FaComment/><mark>🎁 Rs. 2</mark><time>1 day ago</time><strong>2 likes</strong><p>Talibh Rs. 1,419 received via EasyPaisa. Alhamdulillah! 🎉</p></footer></div></Frame>}
export function SalaryLevels(){let levels=[['L1','100K – 199K','1,500'],['L2','200K – 349K','3,000'],['L3','350K – 499K','5,000'],['L4','500K – 749K','8,000'],['L5','750K – 999K','12,000'],['L6','1,000K – 1,499K','18,000'],['L7','1,500K – 1,999K','25,000'],['L8','20L+','35,000']];return <Frame title="Weekly Salary" subtitle="Every Monday · 2:00 AM PKT"><SectionLabel>All Levels</SectionLabel><div className="salary-list">{levels.map(([l,r,v])=><article key={l}><b>{l}</b><div><strong>Level {l.slice(1)}</strong><small>Rs. {r}</small></div><strong>Rs. {v}<small>per week</small></strong><FaLock/></article>)}</div></Frame>}
export function PoolConfirm(){return <Frame title="Dolphin Cove Pool" subtitle="Smart investment · secure future"><div className="pool-cover"><h2>🐬 Dolphin Cove Pool</h2><b>5.0%/day</b></div><div className="confirm-sheet"><h2>Confirm Investment</h2><p>Please review before confirming</p>{[['Pool','🐬 Dolphin Cove Pool'],['Amount','Rs0.00'],['Daily Profit','Rs0.00'],['Total Profit','Rs0.00'],['Duration','48 Days']].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}<button disabled><FaArrowLeft/> Confirm & Invest</button></div></Frame>}
export function TeamRewardsFull(){return <Frame title="Team Rewards" subtitle="Earn bonuses as your team grows" action={<FaTrophy className="gold"/>}><div className="reward-banner"><small>L1 Team Invested</small><strong>Rs. 0</strong><span>Next: Starter at Rs. 10,000</span></div><div className="reward-levels">{[['Gold','100,000','1,500'],['Platinum','200,000','3,500'],['Elite','300,000','6,000'],['Master','500,000','10,000'],['Grand Master','750,000','16,000']].map(x=><article key={x[0]}><span>🔒</span><div><strong>{x[0]}</strong><small>Invest Rs. {x[1]} in L1 team</small></div><b>Rs. {x[2]}</b><ProgressBar/></article>)}</div></Frame>}
export function ProfileSecurity(){const [show,setShow]=useState(false);return <Frame title="Edit Profile" subtitle="Update your account details"><div className="profile-form"><input placeholder="City"/><button>▣ Save Changes</button><SectionLabel>Contact Details</SectionLabel><p>Email Address<br/><strong>itsfarhan259@gmail.com</strong></p><p>Phone Number<br/><strong>03446721559</strong></p></div><div className="security"><SectionLabel>Security</SectionLabel><h2><FaLock/> Change Password</h2>{['Current Password','New Password (8+)','Confirm Password'].map(x=><input key={x} type={show?'text':'password'} placeholder={x} />)}<button onClick={()=>setShow(!show)}><FaLock/> Update Password</button></div></Frame>}
export function DashboardDetail(){return <Frame title="Home"><div className="team-reward-card"><FaTrophy/><strong>Team Rewards</strong><span>0/9</span><small>Next: Starter at Rs. 10,000</small><ProgressBar/></div><div className="dashboard-stats"><b>Rs0.00<small>Today&apos;s Profit</small></b><b>Rs0.00<small>This Month</small></b><b>0<small>Team Members</small></b></div><SectionLabel>Open Pools</SectionLabel><div className="pool-mini"><strong>🐬 Dolphin Cove Pool</strong><span>5.0%/d</span><small>48d · 240.0% total return</small><ProgressBar/></div></Frame>}
