'use client'

import { useState } from 'react'
import { FaArrowDown, FaArrowLeft, FaArrowUp, FaBuildingColumns, FaCamera, FaCheck, FaCircleInfo, FaClock, FaCopy, FaDownload, FaEnvelope, FaGlobe, FaHeart, FaLocationDot, FaPhone, FaRotate, FaShareNodes, FaStar, FaTriangleExclamation, FaTrophy, FaUsers, FaWallet } from 'react-icons/fa6'
import { PageHeader, BottomNav } from './app-shell'
import { BottomSpacing, SectionLabel } from './shared'
import './reference-screens.css'

function RefFrame({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <><PageHeader title={title} subtitle={subtitle}/><main className="ref-content">{children}</main><BottomSpacing/><BottomNav/></> }

export function CommunityScreen() {
  const [tab, setTab] = useState<'chat'|'dm'|'groups'>('chat')
  return <><PageHeader title="Community" subtitle="Connect with EveeRide investors"/><main className="content community-body"><div className="community-tabs">{[['chat','Live Chat'],['dm','DM'],['groups','Groups']].map(([id,label])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={tab===id?'selected':''}>{label}</button>)}</div>{tab==='chat'&&<><SectionLabel>Investor Community</SectionLabel><div className="community-row"><span className="avatar navy">E</span><div><strong>EveeRide Investors <mark>● LIVE</mark></strong><small>3,182 active investors</small></div><FaEnvelope className="row-icon"/></div><p className="community-note">This is the official EveeRide investor community chat. All verified investors can participate.</p></>}{tab==='dm'&&<><SectionLabel>Upliner</SectionLabel><div className="community-row"><span className="avatar orange">S</span><div><strong>SAJID KHAN <mark className="gray">Upliner</mark></strong><small>Tap to start a conversation</small></div><FaEnvelope className="row-icon"/></div></>}{tab==='groups'&&<><div className="section-heading"><SectionLabel>Join a Group</SectionLabel><b>See All</b></div>{[['Saqib Khan\'s Team','7578 members · Saqib Khan'],['Mano\'s Team','4362 members · Mano'],["admin's Team",'4054 members · admin'],["Prince's Team",'3332 members · Prince'],["Mr AB's Team",'2872 members · Mr AB']].map((x,i)=><div className="group-row" key={x[0]}><span className={`avatar ${i%2?'purple':'yellow'}`}>{x[0][0]}</span><div><strong>{x[0]}</strong><small>{x[1]}</small></div><button>Join</button></div>)}<p className="see-all">See all 50 ranked groups →</p></>}</main><BottomSpacing/><BottomNav/></>}

export function AchievementScreen() { return <RefFrame title="Achievement Card" subtitle="Share your success 🏆"><div className="achievement-card"><header><strong>● EVEERIDE</strong><span>🇵🇰 Pakistan</span></header><div className="achievement-avatar"><FaUsers/></div><h2>Muhammad Farhan</h2><p><FaLocationDot/> Your City</p><label>JOIN MY TEAM — USE MY CODE</label><strong className="invite-code">KMSCBCRS</strong><hr/><small>Grow your earnings together with EveeRide</small><b>eveeride.com</b></div><section className="customize-card"><h2>Customize Your Card</h2><div className="fake-input"><FaUsers/> Muhammad Farhan</div><div className="fake-input"><FaLocationDot/> Your City <FaLocationDot className="green"/></div><p>Tap 📍 to auto-detect from your location</p><button className="photo-button"><FaCamera/> Choose Your Photo</button></section><button className="primary-action"><FaDownload/> Download Card</button><button className="secondary-action"><FaShareNodes/> Share Card</button></RefFrame>}

export function ValuesAboutScreen(){return <RefFrame title="About EveeRide" subtitle="Built for investors, by investors"><div className="about-card"><h2><FaHeart/> Our Values</h2>{[['Transparency First','Every fee, every return, every transaction is visible. No hidden surprises.',FaCheck],['Investor-First Always','Every platform decision is evaluated: is this good for our investors?',FaStar],['Halal & Ethical','All investments comply with Islamic finance principles, backed by real assets.',FaWallet],['Continuous Innovation','Constantly improving to serve more Pakistanis with better products.',FaDownload]].map(([a,b,I])=><article key={a as string}><span><I/></span><div><strong>{a as string}</strong><p>{b as string}</p></div></article>)}</div><div className="about-card contact-card"><h2><FaPhone/> Get In Touch</h2><p><FaEnvelope/> Email<br/><strong>support@eveeride.com</strong></p><p><FaGlobe/> Website<br/><strong>eveeride.com</strong></p><p><FaLocationDot/> Office<br/><strong>Lahore, Punjab, Pakistan</strong></p></div><footer>EveeRide © 2024–2026 · Version 1.1</footer></RefFrame>}

export function WithdrawFundsScreen(){return <RefFrame title="Withdraw Funds" subtitle="Transfer to your bank or wallet"><div className="balance-grid"><div>Withdrawable<strong>Rs0.00</strong></div><div><FaWallet aria-hidden="true"/> Capital (Locked)<strong>Rs0.00</strong><small>Deposit · not withdrawable</small></div></div><div className="withdraw-card"><div className="withdraw-summary"><FaRotate aria-hidden="true"/> <div>Daily Withdrawals<strong>2 remaining</strong></div><b>1　2</b></div><div className="withdraw-grid"><div><FaArrowDown aria-hidden="true"/><span>Min<strong>Rs. 100</strong></span></div><div><FaArrowUp aria-hidden="true"/><span>Max<strong>Rs. 50,000</strong></span></div><div><FaClock aria-hidden="true"/><span>Speed<strong>1-60 min</strong></span></div><div><FaBuildingColumns aria-hidden="true"/><span>Via<strong>EP · JC · Bank</strong></span></div></div><p className="warning"><FaTriangleExclamation aria-hidden="true"/> Only profit &amp; bonus balance is withdrawable. Ensure your account details are correct before submitting.</p></div><section className="withdraw-step"><h2><b>1</b> Withdrawal Amount</h2><input placeholder="Amount (Rs.) *"/><p>No withdrawable balance yet. Invest in a pool to start earning daily profits.</p></section><section className="withdraw-step"><h2><b>2</b> Select Account</h2><p className="success"><FaClock aria-hidden="true"/> Auto withdrawal — amount will be sent within 1-60 minutes</p><div className="no-account"><FaBuildingColumns aria-hidden="true"/><strong>No payment account added</strong><span>Add your EasyPaisa, JazzCash or bank account to withdraw</span><button>Add Account</button></div></section><button className="primary-action"><FaWallet aria-hidden="true"/> Submit Withdrawal</button></RefFrame>}
