'use client'

import Link from 'next/link'
import { useState } from 'react'
import { FaArrowTrendUp, FaArrowLeft, FaBell, FaCheck, FaCircleInfo, FaGift, FaLock, FaPlus, FaTrophy, FaUserGroup, FaWallet } from 'react-icons/fa6'
import { BottomNav, PageHeader } from './app-shell'
import { BottomSpacing, EmptyState, IconTile, ProgressBar, SectionLabel } from './shared'
import './remaining-screens.css'

function Screen({ children, title, subtitle, action }: { children: React.ReactNode; title: string; subtitle?: string; action?: React.ReactNode }) {
  return <><PageHeader title={title} subtitle={subtitle} action={action} /><main className="content remaining-content">{children}</main><BottomSpacing /><BottomNav /></>
}

export function PromoScreen() {
  const [code, setCode] = useState('')
  return <Screen title="Promo Code" subtitle="Create or redeem codes for bonus"><div className="member-status"><IconTile tone="gold"><FaUserGroup /></IconTile><div><strong>Free Member</strong><span>No active investment — invest to unlock bigger rewards</span></div><b>Eligible</b></div><div className="white-panel promo-form"><h2><IconTile tone="green"><FaGift /></IconTile>Redeem Promo Code</h2><p>Enter a leader&apos;s code to win bonus</p><input value={code} onChange={e => setCode(e.target.value)} placeholder="Enter 6-digit code" maxLength={6} /><button disabled={code.length !== 6}><FaGift /> Redeem &amp; Win</button><aside>✨ &nbsp; Win Rs. 1–5 bonus!</aside></div><div className="white-panel leader-guide"><h2><IconTile tone="gold"><FaTrophy /></IconTile>How to Become a Leader</h2><p>Create daily promo codes &amp; earn bonuses</p><ProgressLine label="Direct Referrals" value="0/10" /><ProgressLine label="Team Investment" value="Rs. 0/50,000" /></div></Screen>
}
function ProgressLine({ label, value }: { label: string; value: string }) { return <div className="progress-line"><strong>{label}</strong><div><ProgressBar /></div><b>{value}</b></div> }

export function AccountsScreen() { return <Screen title="My Accounts" subtitle="Saved payment accounts" action={<button className="header-add"><FaPlus /> Add</button>}><EmptyState title="No accounts added yet" description="Add a wallet or bank to receive withdrawals" icon={<FaWallet />} /><button className="primary-button compact"><FaPlus /> Add Account</button></Screen> }

export function InviteScreen() { return <Screen title="Invite & Earn" subtitle="Build your team and earn rewards"><div className="invite-stats"><Stat value="0" label="Invites" /><Stat value="Rs0.00" label="Earned" /><Stat value="Rs0.00" label="Today" /></div><div className="white-panel"><h2>✨ &nbsp;How It Works</h2>{[['Share your code','Send invite link via WhatsApp or SMS'],['Friend signs up','They register using your referral code'],['They invest','Commission triggers when they invest in any pool'],['You earn instantly','Commission credited to your bonus balance']].map(([a,b],i)=><div className="step" key={a}><b>{i+1}</b><div><strong>{a}</strong><span>{b}</span></div></div>)}</div><div className="rate-callout"><strong>Up to 6.0% per level</strong><span>See full breakdown on Team tab</span></div></Screen> }
function Stat({ value, label }: { value: string; label: string }) { return <div><strong>{value}</strong><span>{label}</span></div> }

export function LeagueScreen() { const people = [['Haider ali','H',102],['Mubashir M','M',100],['Asif Ali','A',61],['Umar farooq','U',52],['Zulfiqar Ali','Z',42],['M Mubashir Nadeem','M',40],['Noor Nabi Khushik','N',31],['Abbas','A',23]]; return <Screen title="Weekly League" subtitle="Compete every week for prizes"><div className="cohort-title">MY COHORT</div><div className="league-list">{people.map(([name, initial, points],i)=><div className="league-row" key={String(name)}><b>{i+4}</b><span>{initial}</span><div><strong>{name}</strong><small>This week&apos;s points</small></div><em>{points}</em></div>)}</div></Screen> }

export function InvestmentsScreen() { return <Screen title="My Investments" subtitle="Track your portfolio"><div className="invite-stats investment-stats"><Stat value="0" label="Active" /><Stat value="Rs0.00" label="Invested" /><Stat value="Rs0.00" label="Earned" /></div><div className="tab-strip"><b>All</b><span>Active</span><span>Matured</span></div><EmptyState title="No Investments Yet" description="Start growing your wealth by investing in a pool" icon={<FaArrowTrendUp />} /></Screen> }

export function NotificationsScreen() { return <Screen title="Notifications" subtitle="3 unread" action={<button className="mark-read"><FaCheck /> Mark all read</button>}><div className="notification-list">{[['Hi {name} 🚀 EveeRide is Back!','Cycle 2 is officially LIVE! 💚 Start your new journey today. ✨','INFO'],['Hi {name} 🚀 EveeRide is Back!','Cycle 2 is officially LIVE! 💚 Start your new journey today. ✨','SUCCESS'],['Deposit Expired ⏰','Rs. 500 deposit via EASYPAISA was not completed in time. Please try again.','DEPOSIT']].map(([title,body,tag])=><article className="notification" key={title+tag}><IconTile tone={tag==='INFO'?'blue':tag==='SUCCESS'?'green':'pink'}><FaBell /></IconTile><div><strong>{title}</strong><span>{body}</span><small>15 hours ago</small></div><b>{tag}</b></article>)}</div></Screen> }

export function DepositFormScreen() { const [amount,setAmount]=useState(''); return <Screen title="Instant Deposit" subtitle="EasyPaisa / JazzCash — auto credited"><div className="deposit-step"><h2><b>1</b>Select Payment Method</h2><div className="method-grid"><button>EasyPaisa</button><button>JazzCash</button></div></div><div className="deposit-step"><h2><b>2</b>Enter Amount</h2><div className="amount-grid">{['100','200','500','1,000','2,000','5,000','10,000','20,000','50,000'].map(x=><button key={x} onClick={()=>setAmount(x)}>Rs. {x}</button>)}</div><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Rs.  Or type custom amount" /></div><button className="pay-button" disabled={!amount}><FaLock /> Pay Now — Rs. {amount || '0'}</button><div className="white-panel"><h2>▣ &nbsp;Payment Guide</h2><p>Select &amp; Pay — EasyPaisa ya JazzCash select karein, amount daalein aur &quot;Pay Now&quot; tap karein.</p></div></Screen> }

export function PoolDetailScreen() { return <Screen title="Dolphin Cove Pool" subtitle="Smart investment · secure future"><div className="pool-detail-hero"><div><h2>🐬 Dolphin Cove Pool</h2><b>5.0%/day</b></div><div className="pool-stats"><span><strong>48 Days</strong>Duration</span><span><strong>Rs100</strong>Min Invest</span><span><strong>Rs200,000</strong>Max/User</span></div></div><div className="white-panel funding"><h2>◔ &nbsp;Pool Funding <b>42% Filled</b></h2><ProgressBar /><p>Rs4,201,134.25 raised <span>of Rs10,000,000</span></p><div><aside>Available to Invest<strong>Rs5,798,865.75</strong></aside><aside>You Can Invest<strong>Rs100 – Rs200,000</strong></aside></div></div><div className="white-panel"><h2><FaCircleInfo /> About This Pool</h2><p>Where playful waves meet endless opportunities. ⭐</p></div><button className="primary-button invest-button"><FaArrowTrendUp /> Invest Now</button></Screen> }

export function TeamRewardsScreen() { return <Screen title="Team Rewards" subtitle="Earn bonuses as your team grows" action={<FaTrophy className="gold-icon" />}><div className="reward-hero"><div><small>L1 Team Invested</small><strong>Rs. 0</strong><span>Next: Starter at Rs. 10,000</span></div><span>0/9 claimed</span><ProgressBar /></div><div className="how-card"><h2><FaCircleInfo /> How It Works</h2>{['Invite friends and build your Level 1 team','When your L1 team members invest, their total counts towards milestones','Reach a milestone threshold to unlock the reward','Tap Claim to receive the bonus in your wallet instantly','Each milestone can only be claimed once'].map((x,i)=><p key={x}><b>{i+1}</b>{x}</p>)}</div>{[['Starter','Rs. 10,000','Rs. 100'],['Bronze','Rs. 25,000','Rs. 300'],['Silver','Rs. 50,000','Rs. 700'],['Elite','Rs. 300,000','Rs. 6,000']].map(([a,b,c])=><div className="reward-card" key={a}><span className="reward-lock"><FaLock /></span><div><strong>{a}</strong><span>Invest {b} in L1 team</span></div><b>{c}</b><ProgressBar /></div>)}</Screen> }

export function RanksScreen() { const ranks=[['Bronze','Self Rs500.00 · Team Rs0.00','+0.0%'],['Silver','Self Rs5,000.00 · Team Rs10,000.00','+0.5%'],['Gold','Self Rs25,000.00 · Team Rs100,000.00','+1.0%'],['Diamond','Self Rs100,000.00 · Team Rs500,000.00','+2.0%'],['Crown','Self Rs500,000.00 · Team Rs2,500,000.00','+3.0%']]; return <Screen title="Ranks & Rewards" subtitle="Unlock higher daily profit bonuses"><div className="how-card">Both self &amp; team thresholds must be met to unlock a rank. Higher ranks earn extra daily profit bonus.</div><SectionLabel>Rank Ladder</SectionLabel>{ranks.map(([a,b,c])=><div className="rank-card" key={a}><span>🏅</span><div><strong>{a}</strong><small>{b}</small><p>{a} rank. Keep investing to climb higher.</p></div><b>{c}<small>/day</small></b></div>)}</Screen> }

export function TeamScreen() { return <Screen title="Team" subtitle="Grow your network"><SectionLabel>Commission Rates</SectionLabel><div className="commission-grid">{[['L1','6%'],['L2','3%'],['L3','2%'],['L4','1%']].map(([a,b])=><div key={a}><b>{a}</b><strong>{b}</strong><span>commission</span><small>0 members</small></div>)}</div><div className="info-callout"><FaCircleInfo /> Commissions credited instantly to Bonus Balance on every team investment or profit.</div><div className="team-empty"><FaUserGroup /><h2>No Team Members Yet</h2><p>Share your code to build your team</p></div></Screen> }

export function WelcomeAboutScreen() { return <Screen title="EveeRide" subtitle="Pakistan&apos;s Premier Agricultural Investment Platform"><div className="welcome-hero"><div className="mini-mark">E</div><h1>EveeRide</h1><p>Pakistan&apos;s Premier Agricultural Investment Platform</p><div className="welcome-stats"><Stat value="5,000+" label="Members" /><Stat value="Rs.50M+" label="Invested" /><Stat value="99.9%" label="Uptime" /><Stat value="2023" label="Founded" /></div></div><div className="about-card"><h2><IconTile tone="green"><FaCircleInfo /></IconTile>Our Story</h2><p>EveeRide was founded in 2023 with one bold mission: to make agricultural investment accessible to every Pakistani — not just institutions and the ultra-wealthy.</p><p>We built a platform that connects verified agricultural pools with everyday investors.</p></div></Screen> }
