'use client'

import { useState } from 'react'
import Link from 'next/link'
import { FaArrowDown, FaArrowTrendUp, FaArrowUp, FaCalendar, FaCheck, FaCircleInfo, FaClock, FaCopy, FaGear, FaImage, FaLock, FaMagnifyingGlass, FaMobileScreenButton, FaShieldHalved, FaTrophy, FaUsers, FaWallet } from 'react-icons/fa6'
import { BottomNav, PageHeader } from './app-shell'
import { BottomSpacing, EmptyState, IconTile, InfoCallout, MenuRow, ProgressBar, SalaryLevelList, SectionLabel, UpdateItem } from './shared'

function Page({ children, title, subtitle, action }: { children: React.ReactNode; title: string; subtitle?: string; action?: React.ReactNode }) { return <><PageHeader title={title} subtitle={subtitle} action={action} /><main className="content">{children}</main><BottomSpacing /><BottomNav /></> }

export function PoolsScreen() { const [query, setQuery] = useState(''); return <Page title="Investment Pools" subtitle="Find your next growth opportunity" ><div className="search-box"><FaMagnifyingGlass /><input aria-label="Search pools" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search pools..." /></div><div className="filters">{['Open', 'All', 'Running', 'Matured'].map((x, i) => <button className={i === 0 ? 'selected' : ''} key={x}>{x}</button>)}</div><div className="pool-card"><div className="pool-image">DOLPHIN<br /><small>COVE POOL</small><b>5.0% / day</b></div><div className="pool-body"><h2>Dolphin Cove Pool</h2><div className="pool-stats"><span>Duration<strong>48 Days</strong></span><span>Total Return<strong>240%</strong></span><span>Funded<strong>42%</strong></span></div></div></div></Page> }

export function SalaryScreen() { return <Page title="Weekly Salary" subtitle="Every Monday · 2:00 AM PKT"><div className="salary-summary"><ProgressBar /><div><strong>Rs. 0</strong><span>0%</span></div></div><InfoCallout title="Level 1 Team kya hoti hai?">Jo log aap ne seedha apne referral link se invite kiye hain — woh aap ki Level 1 team hai. Unki kul investment se aap ki salary calculate hoti hai.</InfoCallout><InfoCallout title="Salary kab milti hai?"><span>Har Somwar (Monday) raat 2:00 AM Pakistan time pe salary automatically aap ki wallet mein aa jaati hai — agar aap eligible hain to.</span></InfoCallout><SectionLabel>All Levels</SectionLabel><SalaryLevelList /></Page> }

export function RewardsScreen() { const rewards = [['Starter', 'Rs. 10,000', 'Rs. 100'], ['Bronze', 'Rs. 25,000', 'Rs. 300'], ['Silver', 'Rs. 50,000', 'Rs. 700']]; return <Page title="Team Rewards" subtitle="Earn bonuses as your team grows" action={<FaTrophy className="gold-icon" />}><div className="reward-hero"><div><small>L1 Team Invested</small><strong>Rs. 0</strong><span>Next: Starter at Rs. 10,000</span></div><span>0/9 claimed</span><ProgressBar /></div><div className="how-card"><h2><FaCircleInfo /> How It Works</h2>{['Invite friends and build your Level 1 team', 'When your L1 team members invest, their total counts towards milestones', 'Reach a milestone threshold to unlock the reward', 'Tap Claim to receive the bonus in your wallet instantly', 'Each milestone can only be claimed once'].map((x, i) => <p key={x}><b>{i + 1}</b>{x}</p>)}</div>{rewards.map(([name, target, amount]) => <div className="reward-card" key={name}><span className="reward-lock">🔒</span><div><strong>{name}</strong><span>Invest {target} in L1 team</span></div><b>{amount}</b><ProgressBar /></div>)}</Page> }

export function CommissionsScreen() { return <Page title="Commissions" subtitle="Referral earnings history"><EmptyState title="No commissions yet" description="Invite friends to start earning" /></Page> }

export function NewsScreen() { return <Page title="What's New" subtitle="Version history & updates" action={<span className="mini-mark">EX</span>}><div className="version"><strong>v1.8</strong><span>1 August 2026</span><em>Latest</em></div><div className="updates-card"><UpdateItem tone="blue" icon={<FaShieldHalved />} title="Verified Badge">Spot top-tier investors at a glance — verified badges now show in Leagues, Leaderboard, and Chat</UpdateItem><UpdateItem tone="pink" icon={<FaTrophy />} title="New Games — Coin Flip & Plinko">Play 100% fair games — flip a coin or drop the ball for a chance to multiply your bonus balance</UpdateItem></div><div className="version"><strong>v1.7</strong><span>27 July 2026</span><em className="older">Older</em></div><div className="updates-card"><UpdateItem tone="green" icon={<FaUsers />} title="Live Chat Support — New!">Chat with our support team in real time — share images, videos and PDFs right from the app</UpdateItem><UpdateItem tone="purple" icon={<FaMobileScreenButton />} title="Active Sessions Redesign">See your current device at a glance with a cleaner, more compact session list</UpdateItem><UpdateItem tone="blue" icon={<FaWallet />} title="My Accounts Redesign">Your saved wallets and bank accounts now have a fresher, easier-to-read look</UpdateItem></div></Page> }

export function SessionsScreen() { return <Page title="Active Sessions" subtitle="Devices logged into your account"><div className="session-card"><IconTile><FaMobileScreenButton /></IconTile><div><h2>realme RMX3938</h2><strong>● Active now · This device</strong></div><div className="chips"><span>Wi-Fi · 154.192.28.213</span><span>Android · App v1.8</span><span>Android 16</span></div></div><div className="security-note"><FaShieldHalved /> If you see an unfamiliar device, remove it immediately and change your password.</div></Page> }

export function DepositScreen() { return <Page title="Deposit History" subtitle="All your deposit records"><Transaction amount="Rs. 100" status="Pending" date="2026-08-22" id="DP-2026-14819" /><Transaction amount="Rs. 500" status="Rejected" date="2026-08-21" id="DP-2026-14330" /></Page> }
function Transaction({ amount, status, date, id }: { amount: string; status: string; date: string; id: string }) { return <div className="transaction-card"><div className="transaction-top"><IconTile tone={status === 'Pending' ? 'gold' : 'pink'}>{status === 'Pending' ? <FaClock /> : <FaCheck />}</IconTile><div><strong>{amount}</strong><span>ClickPay · EASYPAISA</span></div><b className={`status ${status.toLowerCase()}`}>{status}</b></div><div className="transaction-line"><span>Order ID</span><strong>{id}</strong><FaCopy /></div><div className="transaction-line"><span>Txn ID</span><strong>618918202608221823431234</strong><FaCopy /></div><div className="transaction-line"><span>Date</span><strong>{date}</strong></div><button className="report"><FaCircleInfo /> Report Issue</button></div> }

export function ProfileScreen() { const groups: { label: string; rows: [string, string, string, React.ReactNode][] }[] = [{ label: 'Finance', rows: [['Deposit History', 'All deposit records', '/deposit-history', <FaWallet />], ['Withdrawal History', 'All withdrawal records', '/withdrawal-history', <FaCalendar />], ['Transactions', 'All wallet activity', '/transactions', <FaArrowUp />], ['Commissions', 'Referral earnings history', '/commissions', <FaUsers />], ['My Accounts', 'Saved payment accounts', '/accounts', <FaWallet />]] }, { label: 'Investments & Team', rows: [['My Investments', 'Active pools & returns', '/investments', <FaArrowTrendUp />], ['Team', 'Referral network', '/team', <FaUsers />], ['Ranks', 'Your rank & progress', '/ranks', <FaTrophy />], ['Weekly Salary', 'L1 team salary progress', '/salary', <FaMoneyBillWave />]] }]; return <Page title="Profile" subtitle="Manage your EveeRide account"><div className="profile-banner"><div className="avatar large">MF</div><div><h2>Muhammad Farhan</h2><p>Investor since 2026</p></div><Link href="/edit-profile">Edit</Link></div>{groups.map(group => <div key={group.label}><SectionLabel>{group.label}</SectionLabel><div className="profile-menu-card">{group.rows.map(([title, description, href, icon]) => <MenuRow key={title} title={title} description={description} href={href} icon={icon} />)}</div></div>)}</Page> }

export function EditProfileScreen() { return <Page title="Edit Profile"><div className="edit-hero"><div className="avatar question">?</div><strong>—</strong></div><div className="edit-card"><h2><IconTile tone="blue"><FaUsers /></IconTile>Personal Information</h2><label>Full Name<input placeholder="Full Name" /></label><label>City<input placeholder="City" /></label><button className="primary-button">Save Changes</button><SectionLabel>Contact Details</SectionLabel><MenuRow title="Email Address" description="—" icon={<FaWallet />} /><MenuRow title="Phone Number" description="Not set" icon={<FaMobileScreenButton />} /></div></Page> }

export function AboutScreen() { return <Page title="About EveeRide" subtitle="Our story, mission & values"><div className="about-card"><h2><IconTile tone="green"><FaCircleInfo /></IconTile>Our Story</h2><p>EveeRide was founded in 2023 with one bold mission: to make agricultural investment accessible to every Pakistani — not just institutions and the ultra-wealthy.</p><p>We built a platform that connects verified agricultural pools with everyday investors. Every pool is carefully audited, transparently managed, and designed to deliver consistent daily returns.</p><p>Today, thousands of Pakistanis trust EveeRide as their go-to platform for growing their wealth.</p></div><div className="mission-grid"><div><IconTile tone="blue"><FaFlag /></IconTile><h2>Mission</h2><p>Democratize agricultural investment for every Pakistani.</p></div><div><IconTile tone="purple"><FaEye /></IconTile><h2>Vision</h2><p>Pakistan's most trusted investment platform.</p></div></div></Page> }

function FaMoneyBillWave() { return <FaWallet /> }
function FaFlag() { return <FaArrowTrendUp /> }
function FaEye() { return <FaCircleInfo /> }
